### ISSUE TITLE
Failed to deploy on softlayer

### ISSUE THREAD

**Issue by rs2015** [IBM/deploy-ibm-cloud-private#32]
MACBOOKPRO-20:deploy-ibm-cloud-private rpatel$ ssh root@public-ip docker run -e SL_USERNAME=user -e SL_API_KEY=apikey -e LICENSE=accept --net=host --rm -t -v /root/cluster:/installer/cluster icp-on-sl install
ERROR! Attempted to execute "cluster/hosts" as inventory script: Inventory script (cluster/hosts) had an execution error: Traceback (most recent call last):
  File "/installer/cluster/hosts", line 206, in <module>
    SoftLayerInventory()
  File "/installer/cluster/hosts", line 85, in __init__
    self.get_all_servers()
  File "/installer/cluster/hosts", line 203, in get_all_servers
    self.get_virtual_servers(tags=tags)
  File "/installer/cluster/hosts", line 186, in get_virtual_servers
    instances = vs.list_instances(mask=mask,tags=tags)
  File "/usr/lib/python2.7/site-packages/SoftLayer/managers/vs.py", line 160, in list_instances
    return func(**kwargs)
  File "/usr/lib/python2.7/site-packages/SoftLayer/API.py", line 392, in call_handler
    return self(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/SoftLayer/API.py", line 360, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/SoftLayer/API.py", line 263, in call
    return self.transport(request)
  File "/usr/lib/python2.7/site-packages/SoftLayer/transports.py", line 195, in __call__
    raise _ex(ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception): Invalid IP Address for API key.

**Comment by paulczar** [comment]
this looks like an error from softlayer itself `SoftLayerAPIError(SoftLayer_Exception): Invalid IP Address for API key.`  May need to hunt through SL docs and/or check your credetials are correct.
